Sim coverage
Neves-P/DAISIErobustness pull request #64
Opened 2022-01-05 15:00 UTC by joshwlambert

New parameter spaces and continental island naming.

2022-01-05 16:52 UTC, Neves-P requested changes
Overall I think all is good! I only noted down a couple of things in comments on the PR, these should be very easy to get through (and I'm happy to change things myself). Let me know and I'll approve when done 👍

2022-01-05 16:52 UTC, Neves-P commented on R/all_endemic_clades.R
> +  if (any(stacs == 3)) {
This can be done by calling `any_recols()` unless I'm missing something, no? I'm happy to change if you agree

2022-01-05 16:52 UTC, Neves-P commented on R/calc_ml.R
> +        jitter = 1e-5)
Here `jitter` is 1e-5 and not -1e-5 because anagenesis is fixed to zero (and would go negative), correct?

2022-01-05 18:46 UTC, Neves-P commented
Merged fix in `extdata_alternative` into `sim_coverage` to see if checks pass here too.

2022-01-06 15:10 UTC, Neves-P commented
It seems like the tests fail even after fixing what was failing on `extdata_alternative`. https://github.com/Neves-P/DAISIErobustness/runs/4718858040?check_suite_focus=true#step:9:695
At first glance, the failures are probably related to the changes in the parameter space, as the references should necessarily be different, and the new approach with `all_endemics()` and friends.
@joshwlambert , could you please confirm? And if you agree and address the review comments above too, I'd be happy to fix the references and get this merged to develop and master 👍 🥳

2022-01-14 15:36 UTC, joshwlambert commented
@Neves-P Now the other PR is accepted and sim_coverage is merged with develop are you happy to close this pull request?

2022-01-14 15:45 UTC, Neves-P commented
For sure! Thanks a bunch, closed and made redundant with #65

2022-01-14 15:45 UTC, closed without merging